require('basic')
require('keybindings')
require('plugins')
require('colorscheme')
-- require('lsp.setup')

-- plugins work
require('plugin_config.nvim_tree')
require('plugin_config.bufferline')
require('plugin_config.lualine')
require('plugin_config.telescope')
require('plugin_config.dashboard')
require('plugin_config.project')
require('plugin_config.treesitter')
require('plugin_config.nvim_lspconfig')
require('plugin_config.nvim_lsp_installer')
require('plugin_config.autopairs')
require('plugin_config.autosave')
require('plugin_config.cmp')
require('plugin_config.fidget')
require('plugin_config.lsp_signature')
require('plugin_config.lspsaga')
